version: "3"

services:
  influxdb:
    image: influxdb
    ports:
      - 8086:8086
    volumes:
      - $PWD:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
